### ISSUE TITLE
Looking for firmware and tools

### ISSUE THREAD

**Issue by rbuache** [NSAPlayset/SLOTSCREAMER#1]
Hi,

PLX don't offer anymore the tools and firmware for linux as proposed in your README. 
Could you push them?
Thanks a lot.

R.

**Comment by securelyfitz** [comment]
Looks like they've just move things around. Downloading does require registering on the site.
http://www.plxtech.com/products/sdk/

I can't push the source due to the license on the code. Technically i can redistribute binaries, but Ibelieve that'd be more work than it's worth.

Also, FYI, all the changes to Inception have been pushed upstream.

**Comment by ValdikSS** [comment]
If anyone interested, here you can download PLX SDK 7.10.
https://support.xia.com/default.asp?pg=pgDownload&pgType=pgWikiAttachment&ixAttachment=12071&sFileName=PLX_SDK_Linux_v7_10_Final_2013-08-09.zip

**Comment by securelyfitz** [comment]
Sorry for my delay, I'm travelling.
I don't know if I can give you my copy of the sdk. I will double check
because I inquired about redistribution when I first started the project
but don't recall the answer.
I may not be able to get a solid answer until I'm back at my office in a
other week.

-joe

**Comment by ValdikSS** [comment]
@securelyfitz I found it already on a xia website. It's not the latest one but works perfectly.

**Comment by ValdikSS** [comment]
@securelyfitz I've edited my previous message and I assume you can't see it since you're replying using email.

**Comment by securelyfitz** [comment]
Ah. Thanks. If you haven't already, post the link or instructions and I can
update the guthub/wiki

Good luck!
-joe
